### ISSUE TITLE
guzzlehttp/guzzle 版本问题

### ISSUE THREAD

**Issue by huacoco** [volcengine/ve-tos-php-sdk#24]
你好，该sdk，依赖guzzlehttp/guzzle 版本，是否太低了，在composer其他sdk的时候，通常会遇到冲突的情况。能否升级一下，支持guzzlehttp/guzzle7.0以上的版本？

**Comment by pwz857409056** [comment]
同问，guzzlehttp/guzzle 版本能不能升上去啊

**Comment by chewaiwai** [comment]
近期会升级

**Comment by manier13579** [comment]
我也是，在使用laravel框架，guzzlehttp/guzzle是7.2版本的，装不上该sdk，有什么解决办法吗？

**Comment by xiaoke4869** [comment]
+1 @chewaiwai

**Comment by xiaoke4869** [comment]
手动下载源码，修改包guzzle的版本为 ` "guzzlehttp/guzzle": "^7.0.1"`，通过composer` dump-autoload命令手动引入，这样对sdk使用有影响吗？@chewaiwai

**Comment by pwz857409056** [comment]
> 我也是，在使用laravel框架，guzzlehttp/guzzle是7.2版本的，装不上该sdk，有什么解决办法吗？

整个包复制过来，然后改一下guzzlehttp 的版本，最后用私有composer 仓库引入进去使用就可以了
